language: node_js
sudo: false
node_js:
  - 0.10
before_script:
  - npm rebuild
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: npm test
notifications:
  irc:
    channels:
      - "irc.mozilla.org#payments"
    on_success: change
    on_failure: always
